version: "3.9"

services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: poetry run celery -A app.worker.celery_app.celery worker --loglevel=info
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: autobackend

  redis:
    image: redis:7
